/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mail.Views;

import java.util.ArrayList;
import mail.Category;
import mail.FirmaDecorator;
import mail.Mensaje;
import mail.MensajeComun;
import mail.MensajeDecorator;
import mail.Sistema;
import mail.Usuario;
import mail.UsuarioComponente;

/**
 *
 * @author juliansantaana
 */
public class ViewMailWindow extends javax.swing.JFrame {

    /**
     * Creates new form ViewMailWindow
     */
    private Mensaje message;
    
    public ViewMailWindow() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public ViewMailWindow(Mensaje message){
        this();
        this.message = message;
        refreshViewFromMessage();
    }
    
    public void setMessage(Mensaje message){
        this.message = message;
        refreshViewFromMessage();
    }
    
    private void refreshViewFromMessage(){
        txtFrom.setText(this.message.getRemitente().getNick());
        txtTo.setText(Sistema.getInstance().getMailStringFromUsers(this.message.getDestinatarios()));
        txtSubject.setText(this.message.getAsunto());
        lblCategory.setText(this.message.getCategoria().getName());
        txtMessage.setText(this.message.getContenido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        lblCategoryPreLabel = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnReply = new javax.swing.JButton();
        btnReplyAll = new javax.swing.JButton();
        lblSubject = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("De");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Para");

        txtFrom.setEditable(false);

        txtTo.setEditable(false);

        lblCategoryPreLabel.setText("Categoria: ");

        txtMessage.setEditable(false);
        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        btnReply.setText("Responder");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });

        btnReplyAll.setText("Responder a Todos");
        btnReplyAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyAllActionPerformed(evt);
            }
        });

        lblSubject.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblSubject.setText("Asunto");

        txtSubject.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategoryPreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblSubject)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 281, Short.MAX_VALUE)
                                .addComponent(btnReplyAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReply))
                            .addComponent(txtFrom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTo)
                            .addComponent(txtSubject))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoryPreLabel)
                    .addComponent(lblCategory))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReply)
                    .addComponent(btnReplyAll))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
        // TODO add your handling code here:
        MensajeComun msg = new MensajeComun();
        ArrayList<UsuarioComponente> destinatarios = new ArrayList<UsuarioComponente>();
        destinatarios.add(this.message.getRemitente());
        msg.setDestinatarios(destinatarios);
        msg.setRemitente(Sistema.getInstance().getCurrentUser());
        msg.setAsunto("RE:" + this.message.getAsunto());
        msg.setCategoria(this.message.getCategoria());
        msg.setUrgent(this.message.isUrgent());
        
        //setting parent
        msg.setReplyTo(this.message);
        
        ComposeMailWindow compose = new ComposeMailWindow(msg);
        compose.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReplyActionPerformed

    private void btnReplyAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyAllActionPerformed
        // TODO add your handling code here:
        MensajeComun msg = new MensajeComun();
        
        //reply to all: reply to all the users and also to the one that sent the email
        //checking if the user is not already inside the arraylist (to avoid sending the email twice)
        ArrayList<UsuarioComponente> destinatarios = this.message.getDestinatarios();
        if (!destinatarios.contains(this.message.getRemitente())){
            destinatarios.add(this.message.getRemitente());
        }
        
        msg.setDestinatarios(destinatarios);
        msg.setRemitente(Sistema.getInstance().getCurrentUser());
        msg.setAsunto("RE:" + this.message.getAsunto());
        msg.setCategoria(this.message.getCategoria());
        msg.setUrgent(this.message.isUrgent());
        
        //setting parent
        msg.setReplyTo(this.message);
        
        ComposeMailWindow compose = new ComposeMailWindow(msg);
        compose.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReplyAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMailWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReply;
    private javax.swing.JButton btnReplyAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategoryPreLabel;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
